-- Employee profile addresses belong to the system, not to the employee form.
-- Existing slugs and public links remain unchanged; only new rows receive this default.
alter table public.employees
  alter column slug set default ('profile-' || encode(extensions.gen_random_bytes(10), 'hex'));

comment on column public.employees.slug is
  'Opaque permanent public-profile identifier generated by the system; not administrator editable.';
